# use a Mac OSX image
os: osx
# only run builds on pushes to the master branch
branches:
  only:
  - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

# run the script to download and install Unity editor using Homebrew's python (openssl)
install:
  - brew update
  - brew upgrade openssl
  - brew link --force openssl
  - sudo /usr/local/bin/python2 scripts/install-unity.py 2017.2
  - pip install -U pytest

# run the script for unit tests and builds
jobs:
  include:
    - stage: integration
      language: python
      script: sh scripts/integration.sh
    - stage: unit
      script: sh scripts/test.sh
      language: generic
