# do not install anything extra onto the image
language: generic

# use a Mac OSX image
os: osx
# only run builds on pushes to the master branch
branches:
  only:
  - master
  - fix/warnings

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

# run the script to download and install Unity editor using Homebrew's python (openssl)
install:
  - brew update
  - brew upgrade openssl
  - brew link --force openssl
  - sudo /usr/local/bin/python2 scripts/install-unity.py 2017.2

# run the script for unit tests and builds
script:
  - sh scripts/test.sh
